services:
  mvbackend_test:
    build: .
    restart: always
    ports:
      - "8000:443"
    environment:
      NODE_ENV: "test"
      DB_USER: "MvDB"
      DB_PASS:  "MvDB"
      JWT_SECRET: "MySuperSecret"
      JWT_SECRET_REFRESH: "MySuperSecretRefresh"
    volumes:
      - ./SSL:/etc/ssl/mv:ro
      - mvBackend_media_test:/app/public 
    depends_on:
      mvdb_test:
        condition: service_healthy
  mvdb_test:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "MvDB"
      POSTGRES_USER: "MvDB"
      POSTGRES_PASSWORD: "MvDB"
    volumes:
    - mvdb_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  mvBackend_media_test:
  mvdb_data_test: