services:
  MvBackend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=prod
      - PORT=8000
      - DB_USER=<usuario>
      - DB_USER_PASS=<senha_super_secreta>
      - DB_IP=<ip_do_seu_DB>
      - DB_PORT=5432
      - DB_NAME=MvDB