services:
  mvbackend_dev:
    build: .
    ports:
      - "8000:80"
    environment:
      - DB_USER_PASS= MySecretPassword
      - JWT_SECRET= MySuperSecret
      - JWT_SECRET_REFRESH= MySuperSecretRefresh
    depends_on:
      mvdb:
        condition: service_healthy
  mvdb_dev:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD= MySecretPassword
    volumes:
    - mvdb_data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  mvdb_data_dev: