services:
  mvbackend_dev:
    build: .
    restart: always
    command: ["npm", "run", "migrations:run"]
    ports:
      - "8000:443"
    environment:
      - NODE_ENV= test
      - DB_USER_PASS= MySecretPassword
      - JWT_SECRET= MySuperSecret
      - JWT_SECRET_REFRESH= MySuperSecretRefresh
    volumes:
      - ./SSL:/etc/ssl/mv:ro
      - mvBackend_media_dev:/app/public 
    depends_on:
      mvdb_dev:
        condition: service_healthy
  mvdb_dev:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD= MySecretPassword
    volumes:
    - mvdb_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  mvBackend_media_dev:
  mvdb_data_dev: